In [10]:
import torch
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [34]:
siec = torch.nn.Sequential(
    torch.nn.Linear(1, 5),
    torch.nn.Sigmoid(),
    torch.nn.Linear(5, 5),
    torch.nn.Sigmoid(),
    torch.nn.Linear(5,1),
)
optim = torch.optim.Adam(params=siec.parameters(), lr = 0.01)
df = pd.read_csv("/home/pawel/studia/MIOwAD/MIOwAD_labs/mio1/regression/square-simple-test.csv")
X = torch.from_numpy(np.asarray(df["x"]).reshape((-1,1))).float()
y = torch.from_numpy(np.asarray(df["y"]).reshape((-1,1))).float()
for step in range(1,100000):
    y_hat = siec(X)
    loss = (y_hat-y).pow(2).mean()
    print(step, loss.item())
    optim.zero_grad()
    loss.backward()
    # optim.step(lambda : (siec(X)-y).pow(2).mean())
    optim.step()




1 8694.1259765625
2 8690.4296875
3 8686.7255859375
4 8683.009765625
5 8679.287109375
6 8675.5546875
7 8671.818359375
8 8668.0751953125
9 8664.3271484375
10 8660.57421875
11 8656.8154296875
12 8653.052734375
13 8649.2822265625
14 8645.5048828125
15 8641.71875
16 8637.9228515625
17 8634.1123046875
18 8630.28515625
19 8626.4375
20 8622.56640625
21 8618.666015625
22 8614.7333984375
23 8610.7626953125
24 8606.7509765625
25 8602.693359375
26 8598.5888671875
27 8594.431640625
28 8590.220703125
29 8585.9541015625
30 8581.6298828125
31 8577.2451171875
32 8572.8017578125
33 8568.2978515625
34 8563.73046875
35 8559.1025390625
36 8554.412109375
37 8549.662109375
38 8544.849609375
39 8539.9775390625
40 8535.0478515625
41 8530.0595703125
42 8525.015625
43 8519.91796875
44 8514.7685546875
45 8509.5703125
46 8504.3271484375
47 8499.0390625
48 8493.712890625
49 8488.3505859375
50 8482.9560546875
51 8477.533203125
52 8472.0849609375
53 8466.6171875
54 8461.130859375
55 8455.634765625
56 8450.1279296875


In [35]:
for i in siec.parameters():
    print(i)

Parameter containing:
tensor([[ -5.3381],
        [ -1.2753],
        [ -4.3002],
        [-21.0019],
        [ -8.5443]], requires_grad=True)
Parameter containing:
tensor([ 1.4595, -2.0847,  5.3267, 42.6468, 16.2957], requires_grad=True)
Parameter containing:
tensor([[ 10.5775,  -2.8416,   1.5680,  16.8754,  -2.9224],
        [  2.3616, -16.7397,   7.5676,   3.1040,   3.5625],
        [  2.2611, -20.8859,   3.0553,   7.7675,   6.8939],
        [  6.7120, -25.3992,   6.7228,   4.9615,   5.7341],
        [  6.9819, -31.3709,  10.4192,   5.9040,   7.1255]],
       requires_grad=True)
Parameter containing:
tensor([-14.7321, -13.1291, -13.0058, -13.1236, -14.0321], requires_grad=True)
Parameter containing:
tensor([[-56.2364, -99.7419, -75.8010, -77.9080, -73.2831]],
       requires_grad=True)
Parameter containing:
tensor([227.5033], requires_grad=True)


In [ ]:
X.shape

In [ ]:
y.shape

In [24]:
siec(X)

tensor([[ -45.1729],
        [   5.5223],
        [-128.1005],
        [   7.0424],
        [ -28.1429],
        [  36.1042],
        [ -56.0969],
        [ 165.1954],
        [-109.1679],
        [ -45.4875],
        [ -39.0035],
        [-117.4400],
        [   6.6136],
        [-130.6129],
        [ -61.4644],
        [   4.3229],
        [ -65.0042],
        [  44.4927],
        [ -36.7000],
        [ -60.7430],
        [ 154.4589],
        [-113.3768],
        [ -96.7383],
        [ -69.5947],
        [-117.3316],
        [ -60.8222],
        [-128.5401],
        [-115.5303],
        [ -21.8218],
        [ -64.1153],
        [ -31.0580],
        [-129.9839],
        [-129.9054],
        [-127.5145],
        [-129.4202],
        [ -37.2913],
        [  41.8218],
        [-101.0826],
        [  18.5780],
        [  -0.8909],
        [ 136.2709],
        [  76.1451],
        [-115.5091],
        [ -99.8364],
        [ -21.4355],
        [ -17.5251],
        [ 136.1056],
        [  17

In [25]:
siec

Sequential(
  (0): Linear(in_features=1, out_features=5, bias=True)
  (1): ReLU()
  (2): Linear(in_features=5, out_features=5, bias=True)
  (3): ReLU()
  (4): Linear(in_features=5, out_features=1, bias=True)
)